language:
  - cpp

compiler:
  - gcc

script:
  - cmake CMakeLists.txt -DGUI=OFF -DDEBUG=ON -DO=OFF
  - make
  - ./build/nevil -tn 1 -ps 20 -mg 5 -xn SiblingTrial -sn true
  - ./build/nevil -mt 10 -ps 20 -mg 5 -xn SiblingTrial -sn true

  - cmake CMakeLists.txt -DGUI=OFF -DDEBUG=OFF -DO=ON
  - make

  - cmake CMakeLists.txt -DGUI=ON -DDEBUG=ON -DO=OFF
  - make

  - cmake CMakeLists.txt -DGUI=ON -DDEBUG=OFF -DO=ON
  - make